### ISSUE TITLE
Welcome message

### ISSUE THREAD

**Issue by volodinSergey** [Faina5/BotWeather#1]
Hello from Serezha, welcome to GitHub))

**Comment by Faina5** [comment]
### **_HELLOOO!!!_**

**Comment by Faina5** [comment]
> Hello from Serezha, welcome to GitHub))

Thats so nice of you ^^

**Comment by volodinSergey** [comment]
Когда будешь больших ботов писать?

**Comment by Faina5** [comment]
> Когда будешь больших ботов писать?

Когда стану Большим боссом В-)

**Comment by volodinSergey** [comment]
> > Когда будешь больших ботов писать?
> 
> Когда стану Большим боссом В-)

Оки, решили вопросик, закрыли тему 🤪
